// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"honeypot/internal/biz"
	"honeypot/internal/conf"
	"honeypot/internal/data"
	"honeypot/internal/server"
	"honeypot/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	clientRepo := data.NewClientRepo(dataData, logger)
	clientUseCase := biz.NewClientUseCase(clientRepo, logger)
	clientService := service.NewClientService(clientUseCase, logger)
	adminRepo := data.NewAdminRepo(dataData, logger)
	adminUseCase := biz.NewAdminUseCase(adminRepo, logger)
	adminService := service.NewAdminService(adminUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, clientService, adminService, logger)
	httpServer := server.NewHTTPServer(confServer, clientService, adminService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
