// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// { "code":404,
// "reason":"SPY_LOGIN_PASSWORD_MISSING",
// "message":"未填写用户名!",
// "metadata":{}
// }
func IsSaveSpyLoginFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SAVE_SPY_LOGIN_FAILED.String() && e.Code == 404
}

// { "code":404,
// "reason":"SPY_LOGIN_PASSWORD_MISSING",
// "message":"未填写用户名!",
// "metadata":{}
// }
func ErrorSaveSpyLoginFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_SAVE_SPY_LOGIN_FAILED.String(), fmt.Sprintf(format, args...))
}
