version: "3.9"
services:
  nginx:
    image: nginx
    container_name: honeypotNG
    ports:
      - "24000:80"
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
  db:
    image: postgres
    container_name: honeypotPG
    ports:
      - "24001:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: L6CcD4oIWVutd9vDqZC3d1ppK8zB1UNq
  redis:
    image: redis
    container_name: honeypotRds
    ports:
      - "24002:6379"
    environment:
      REDIS_PASSWORD: L6CcD4oIWVutd9vDqZC3d1ppK8zB1UNq



